object GradleConst {
    const val KEY_STORE_PATH = "../buildSrc/keystore/debug.keystore"
    const val DEBUG_KEY_STORE_PATH = "../buildSrc/keystore/debug.keystore"
    const val STORE_PASSWORD = "STORE_PASSWORD"
    const val DEBUG_STORE_PASSWORD = "android"
    const val LIFESTYLE = "blue"
    const val android = "android"
    const val BEAUTY = "pink"
    const val DEBUG_KEY_ALIAS = "androiddebugkey"
    const val KEY_PASSWORD = "KEY_PASSWORD"
    const val DEBUG_KEY_PASSWORD = "android"
    const val RELEASE_CONFIG_BLUE = "releaseConfigBlue"
    const val RELEASE_CONFIG_PINK = "releaseConfigPink"
    const val DEBUG_CONFIG = "DEBUG_CONFIG"

    const val PRODUCT_FLAVOR_BLUE_RELEASE = "bluerelease"
    const val PRODUCT_FLAVOR_BLUE_DEV = "bluedev"
    const val PRODUCT_FLAVOR_BLUE_PD = "bluepd"
    const val PRODUCT_FLAVOR_BLUE_UAT = "blueuat"
    const val PRODUCT_FLAVOR_BLUE_PREPROD = "bluepreprod"

    const val PRODUCT_FLAVOR_PINK_RELEASE = "pinkrelease"
    const val PRODUCT_FLAVOR_PINK_DEV = "pinkdev"
    const val PRODUCT_FLAVOR_PINK_PD = "pinkpd"
    const val PRODUCT_FLAVOR_PINK_UAT = "pinkuat"
    const val PRODUCT_FLAVOR_PINK_PREPROD = "pinkpreprod"

    const val APPLICATION_ID_PINK_RELEASE = "com.freeman.pink"
    const val APPLICATION_ID_PINK_DEV = "com.freeman.pink.dev"
    const val APPLICATION_ID_PINK_UAT = "com.freeman.pink.uat"
    const val APPLICATION_ID_PINK_PREPROD = "com.freeman.pink.preprod"

    const val APPLICATION_ID_BLUE_RELEASE = "com.freeman.blue"
    const val APPLICATION_ID_BLUE_DEV = "com.freeman.bluedev"
    const val APPLICATION_ID_BLUE_UAT = "com.freeman.blueuat"

    const val BUILD_TYPE_DEBUG = "debug"
    const val BUILD_TYPE_RELEASE = "release"
    const val BUILD_TYPE_DEV = "dev"
    const val BUILD_TYPE_PD = "pd"
    const val BUILD_TYPE_UAT = "uat"
    const val BUILD_TYPE_PREPROD = "preprod"
}